
server:
  port: 8766
  servlet:
    context-path: /api

spring:
  application:
    name: service-ht

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

mygit: 妖气0805
