
server:
  port: 8703
  servlet:
    context-path: /api

spring:
  application:
    name: service-ht

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

mygit: 妖气0805
